version: 2
updates:
  # Monitorar dependências Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    reviewers:
      - "afonsolelis"
    assignees:
      - "afonsolelis"
    open-pull-requests-limit: 5
    
  # Monitorar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"